Configure Node server to forward requests to Pulsar
datastax/pulsar-admin-console pull request #56
Opened 2022-05-24 16:35 UTC by mfortman11

How to set it up (this is will be added to the README when the other tasks are also completed)

1. Run pulsar standalone `docker run -it -p 6650:6650  -p 8080:8080 --mount source=pulsardata,target=/pulsar/data --mount source=pulsarconf,target=/pulsar/conf apachepulsar/pulsar:2.8.3 bin/pulsar standalone`
2.  Optional: If rerunning pulsar standalone on a different port that than `8080` above go to `server/config.js` and update the `PULSAR_URL`
3. Start the server (`cd server` and `npm run start`)
4. Run the console (`cd dashboard` and `npm run serve`)

2022-05-24 17:13 UTC, cdbartholomew requested changes

2022-05-24 17:13 UTC, cdbartholomew commented on server/server.js
> +app.use('/api/v1/standalone/functions', createProxyMiddleware({
The name of the cluster, ie `standalone`, needs to be passed in by configuration. From what I can tell, this code will only work with a development Pulsar instance. For example, in Kubernetes, the default cluster name is `pulsar` and the endpoints need to be in the form `/api/v1/pulsar/functions` and the rewrite needs to strip out `pulsar` and change the endpoint to `/admin/v3` (in the case of functions).

2022-05-24 17:13 UTC, cdbartholomew commented on server/server.js
> +app.use('/api/v1/standalone/functions', createProxyMiddleware({
There are 2 places in the `dashboard/public/config.js` file to configure the cluster name:
    "home_cluster": "standalone",
    "cluster_list": ["standalone"],
There is code to support multiple clusters, but it is not fully exposed. So this is just a list of 1 cluster. The "home_cluster" is the one it starts at on the list.

2022-05-24 21:43 UTC, cdbartholomew commented on server/server.js
> +  target: 'http://localhost:8080',
I think this should be set to `cfg.serverConfig.PULSAR_URL`, not localhost.

2022-05-24 21:56 UTC, cdbartholomew commented on server/config.js
>      'LOG_LEVEL': 'info',
To completely remove nginx, the server will also have to support TLS. Previously, nginx was providing that ability. There are default certs used by nginx and the vue dev server that can be used to test TLS configuration.

2022-05-24 22:02 UTC, cdbartholomew commented on server/config.js
>      'LOG_LEVEL': 'info',
Actually, it looks like the server might already support TLS.

2022-05-25 18:54 UTC, mfortman11 commented
All config options are now in `dashboard/public/config.js`

2022-05-26 14:20 UTC, merged